/** The script a published page runs, bundled into the Worker.
 *
 *  A page's own behaviour - the slash that focuses the search box, the theme
 *  toggle, the card a link shows on hover, the graph - is written once, in
 *  `apps/desktop/src/site/site.ts`, and imports the app's own graph layout and
 *  painter rather than a second copy of them. This turns that into one file the
 *  Worker can serve from the site's own domain.
 *
 *  Why the Worker carries it rather than a CDN: the same reason it carries
 *  KaTeX's faces. A script fetched from somebody else's domain tells them who is
 *  reading what, and it breaks for anybody offline or behind a blocker. Served
 *  at a path that is its own hash, cached forever, so a reader fetches it once
 *  for a whole blog.
 *
 *  Run `pnpm blog:js` after changing the site script or anything it imports.
 *  What it writes is committed, so the Worker needs no build step of its own,
 *  and `services/sync/test/site-script.test.ts` fails if the two have drifted.
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = new URL('../', import.meta.url)
const ENTRY = fileURLToPath(new URL('apps/desktop/src/site/site.ts', ROOT))
const TARGET = fileURLToPath(new URL('services/sync/src/blog/script.ts', ROOT))

/** Every file the bundle is made of, for the staleness check: the entry and the
 *  app modules it imports. Named rather than walked, because a walk over every
 *  import of the app would be the app. */
export const SOURCES = [
  'apps/desktop/src/site/site.ts',
  'apps/desktop/src/lib/camera.ts',
  'apps/desktop/src/lib/graph.ts',
  'apps/desktop/src/lib/graph-layout.ts',
  'apps/desktop/src/lib/graph-paint.ts',
]

/** What the sources add up to, so a generated module can say which ones it was
 *  built from and a test can say whether that is still true. */
export function sourceHash(): string {
  const hash = createHash('sha256')
  for (const name of SOURCES) hash.update(readFileSync(fileURLToPath(new URL(name, ROOT))))

  return hash.digest('hex').slice(0, 16)
}

/** The bundle: one file, no imports, minified, for a browser.
 *
 *  Vite rather than a bundler of its own, because the app is built with vite and
 *  the modules being bundled are the app's: one toolchain decides what "the same
 *  code" means. In memory - nothing is written to disk but the module below. */
async function bundle(): Promise<string> {
  // Vite as the app's own copy of it, resolved rather than imported: it is a
  // dependency of the app whose modules are being bundled, and one toolchain is
  // what makes "the same code" mean something. The same way blog-css.ts reaches
  // for the katex the app renders with.
  const vite = (await import(
    pathToFileURL(
      createRequire(fileURLToPath(new URL('apps/desktop/package.json', ROOT))).resolve('vite'),
    ).href
  )) as typeof import('vite')

  const out = await vite.build({
    root: fileURLToPath(ROOT),
    logLevel: 'warn',
    configFile: false,
    build: {
      write: false,
      target: 'es2022',
      minify: 'esbuild',
      lib: { entry: ENTRY, formats: ['iife'], name: 'nibSite', fileName: () => 'site.js' },
    },
  })

  const chunks = Array.isArray(out) ? out : [out]
  for (const one of chunks) {
    if (!('output' in one)) continue
    for (const file of one.output) {
      if (file.type === 'chunk' && file.isEntry) return file.code
    }
  }

  throw new Error('the site script bundled to nothing')
}

/** The one line that puts the reader's chosen theme on the page before it is
 *  painted.
 *
 *  Inline, and the only inline script a site carries: the alternative is a page
 *  that paints in the wrong scheme and then corrects itself, which is the flash
 *  every site with a theme toggle used to have. The policy names it by the hash
 *  of these very characters, so this script may run and no other inline one can;
 *  see `csp` in blog.ts. */
const THEME_JS =
  "try{var t=localStorage.getItem('nib:site-theme');if(t)document.documentElement.setAttribute('data-theme',t)}catch(e){}"

export async function siteScript(): Promise<string> {
  const code = await bundle()
  const path = `/s/${createHash('sha256').update(code).digest('hex').slice(0, 16)}.js`

  return `/* Generated by scripts/site-js.ts from apps/desktop/src/site/site.ts.
 * Do not edit: run \`pnpm blog:js\`. site-script.test.ts fails if it is stale.
 *
 * What a published page does in a browser, bundled with the app's own graph
 * layout and painter inside it. Served from the site's own domain at a path that
 * is its own hash - never from a CDN, for the reason the KaTeX faces are not
 * either. A page that carries none of the things it drives does not link it. */

export const SITE_JS = ${JSON.stringify(code)}

/** The one inline script a page carries, and the hash the policy names it by. */
export const THEME_JS = ${JSON.stringify(THEME_JS)}

export const THEME_JS_HASH = ${JSON.stringify(
    `sha256-${createHash('sha256').update(THEME_JS).digest('base64')}`,
  )}

export const SITE_JS_PATH = ${JSON.stringify(path)}

/** What the sources added up to when this was built; see scripts/site-js.ts. */
export const SITE_JS_SOURCES = ${JSON.stringify(sourceHash())}
`
}

// Run rather than imported. `argv[1]` is the path as it was typed, so both
// sides are resolved before they are compared.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const written = await siteScript()
  writeFileSync(TARGET, written)
  console.log(`wrote ${TARGET} (${(written.length / 1024).toFixed(1)}kB)`)
}
